language: python
python:
  - "3.5"

install:
  - pip install coveralls
  - pip install coverage
  - pip install nose
script: 
  - make test
  - nosetests --with-coverage
after_success:
  - coveralls

